version: '3.5'

services:
  db:
    image: postgres:16.1
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
